asp.net core empty task/Models/Footer.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace asp.net_core_empty_task.Models
{
    public class Footer
    {
        public int id { get; set; }

        [Column("LinkedinUrl")]
        [MaxLength(200)]
        public string Linkedin { get; set; }

        [Column("FacebookUrl")]
        [MaxLength(200)]
        public string Facebook { get; set; }

        [Column("LogoUrl")]
        [MaxLength(200)]
        public string Logo { get; set; }

        [NotMapped]
        public IFormFile Photo { get; set; }
    }
}

asp.net core empty task/Areas/Admin/Controllers/FooterController.cs
using asp.net_core_empty_task.DAL;
using asp.net_core_empty_task.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace asp.net_core_empty_task.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize()]
    public class FooterController : Controller
    {
        private AppDbContext _context;
        private IWebHostEnvironment _env;

        public FooterController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        [HttpGet]
        public IActionResult Index()
        {
            Footer footer = _context.Footer.FirstOrDefault();
            return View(footer);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(Footer footer)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }

            if (!footer.Photo.ContentType.Contains("image"))
            {
                ModelState.AddModelError("photo", "unsupported file type!");
                return View();
            }

            if (footer.Photo.Length > 1024 * 1000)
            {
                ModelState.AddModelError("photo", "file size must be lower than 1mb!");
                return View();
            }

            string filename = footer.Photo.FileName;
            string wwwroot = _env.WebRootPath;

            string path = Path.Combine(wwwroot, "img", filename);

            FileStream stream = new FileStream(path, FileMode.Create);

            await footer.Photo.CopyToAsync(stream);

            stream.Close();

            var _footer = _context.Footer.FirstOrDefault();

            _footer.Logo = footer.Photo.FileName;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

asp.net core empty task/Areas/Admin/Views/Footer/Index.cshtml
@model Footer

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Edit Header</h4>
            <form class="forms-sample" asp-controller="Footer" asp-action="Index" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="exampleInputUsername1" asp-for="Photo">Logo</label>
                    <input type="file" accept="image/*" class="form-control" placeholder="Logo Url" asp-for="Photo">
                    <span class="text-danger" asp-validation-for="Photo"></span>
                </div>
                <div class="form-group">
                    <label for="exampleInputUsername1" asp-for="Facebook">Facebook Url</label>
                    <input type="text" class="form-control" placeholder="Facebook Url" asp-for="Facebook" value="@Model?.Facebook">
                    <span class="text-danger" asp-validation-for="Facebook"></span>
                </div>
                <div class="form-group">
                    <label for="exampleInputUsername1" asp-for="Linkedin">Linkedin Url</label>
                    <input type="text" class="form-control" placeholder="Linkedin Url" asp-for="Linkedin" value="@Model?.Linkedin">
                    <span class="text-danger" asp-validation-for="Linkedin"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
            </form>
        </div>
    </div>
</div>