asp.net core empty task/Models/Slider.cs
using System.Collections.Generic;

namespace asp.net_core_empty_task.Models
{
    public class Slider
    {
        public int id { get; set; }
        public string title { get; set; }
        public string desc { get; set; }
        public string logo { get; set; }

        public List<SliderItem> sliderItems { get; set; }
    }
}

asp.net core empty task/Areas/Admin/Controllers/SliderController.cs
using asp.net_core_empty_task.Areas.Admin.ViewModels;
using asp.net_core_empty_task.DAL;
using asp.net_core_empty_task.Models;
using asp.net_core_empty_task.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace asp.net_core_empty_task.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize()]
    public class SliderController : Controller
    {
        private AppDbContext _context;
        private IWebHostEnvironment _env;

        public SliderController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List()
        {
            var model = await _context.SliderItem.ToListAsync();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(SliderItem sliderItem)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (!sliderItem.Photo.ContentType.Contains("image"))
            {
                ModelState.AddModelError("Photo", "Unsupported File Type!");
                return View();
            }

            if (sliderItem.Photo.Length > 1024 * 1000)
            {
                ModelState.AddModelError("Photo", "File size must be lower than 1mb!");
                return View();
            }

            string FileName = sliderItem.Photo.FileName;
            string wwwRoot = _env.WebRootPath;

            string path = Path.Combine(wwwRoot, "img", FileName);

            FileStream stream = new FileStream(path, FileMode.Create);

            await sliderItem.Photo.CopyToAsync(stream);

            stream.Close();

            sliderItem.image = sliderItem.Photo.FileName;
            await _context.SliderItem.AddAsync(sliderItem);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var item = await _context.SliderItem.FindAsync(id);

            if (item == null)
            {
                return NotFound();
            }

            _context.SliderItem.Remove(item);
            await _context.SaveChangesAsync();

            string wwwRoot = _env.WebRootPath;
            string filePath = item.image;

            string finalPath = Path.Combine(wwwRoot, "img", filePath);

            await FileUtils.Delete(finalPath);

            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            return View();
        }

        [HttpPost]
        [ActionName("Edit")]
        public async Task<IActionResult> EditSliderItem(SliderItem _item)
        {
            var item = await _context.SliderItem.FindAsync(_item.id);

            if (item == null)
            {
                return NotFound();
            }
            string FileName = _item.Photo.FileName;
            string wwwRoot = _env.WebRootPath;

            string path = Path.Combine(wwwRoot, "img", FileName);
            string oldPath = Path.Combine(wwwRoot, "img", item.image);


            await FileUtils.Delete(oldPath);

            FileStream stream = new FileStream(path, FileMode.Create);

            await _item.Photo.CopyToAsync(stream);

            stream.Close();


            item.image = _item.Photo.FileName;
            await _context.SaveChangesAsync();

            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> AddSlider()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> AddMultiple(SliderMultipleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var slider = new Slider { desc = "Default Description", logo = "Default Logo", title = "Default Title" };
            await _context.Slider.AddAsync(slider);
            await _context.SaveChangesAsync();

            foreach (var item in model.sliderItems)
            {

                if (!item.ContentType.Contains("image"))
                {
                    ModelState.AddModelError("Photo", "Unsupported File Type!");
                    return View();
                }

                if (item.Length > 1024 * 1000)
                {
                    ModelState.AddModelError("Photo", "File size must be lower than 1mb!");
                    return View();
                }

                string FileName = item.FileName;
                string wwwRoot = _env.WebRootPath;

                string path = Path.Combine(wwwRoot, "img", FileName);

                FileStream stream = new FileStream(path, FileMode.Create);

                await item.CopyToAsync(stream);

                stream.Close();

                var sliderItem = new SliderItem { image = item.FileName, slider = slider };

                await _context.SliderItem.AddAsync(sliderItem);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

    }
}

asp.net core empty task/Areas/Admin/Views/Slider/AddSlider.cshtml
@model SliderMultipleViewModel

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Category Creation Form</h4>
            <form class="forms-sample" enctype="multipart/form-data" method="post" asp-controller="Slider" asp-action="AddMultiple">
                <div class="form-group">
                    <label for="exampleInputUsername1" asp-for="sliderItems">Name</label>
                    <input type="file" accept="image/*" multiple class="form-control" asp-for="sliderItems" placeholder="Photo">
                    <span class="text-danger" asp-validation-for="sliderItems"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
            </form>
        </div>
    </div>
</div>

asp.net core empty task/Areas/Admin/Views/Slider/Edit.cshtml
@model SliderItem

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Category Creation Form</h4>
            <form class="forms-sample" enctype="multipart/form-data" method="post" asp-controller="Slider" asp-action="Edit">
                <div class="form-group">
                    <label for="exampleInputUsername1" asp-for="Photo">Name</label>
                    <input type="file" accept="image/*" class="form-control" placeholder="Photo" asp-for="Photo">
                    <span class="text-danger" asp-validation-for="Photo"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
            </form>
        </div>
    </div>
</div>

asp.net core empty task/Areas/Admin/Views/Slider/Index.cshtml
@model SliderItem

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Category Creation Form</h4>
            <form class="forms-sample" asp-controller="Slider" asp-action="Index" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="exampleInputUsername1" asp-for="Photo">Photo</label>
                    <input type="file" accept="image/*" class="form-control" placeholder="Photo" asp-for="Photo">
                    <span class="text-danger" asp-validation-for="Photo"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
            </form>
        </div>
    </div>
</div>

asp.net core empty task/Areas/Admin/Views/Slider/List.cshtml
@model List<SliderItem>

<div class="d-flex flex-column gap-5">
    @foreach (var item in @Model)
    {
        <div class="d-flex align-items-center gap-5">
            <img src="~/img/@item.image" style="width:250px; height:100px; object-fit:cover; object-position:center;" />
            <a asp-controller="Slider" asp-action="Edit" asp-route-id="@item.id">
                <button class="btn btn-sm btn-primary">Edit</button>
            </a>
            <a asp-controller="Slider" asp-action="Delete" asp-route-id="@item.id">
                <button class="btn btn-sm btn-danger">Delete</button>
            </a>
        </div>
    }
</div>

asp.net core empty task/Areas/Admin/Views/Slider/Update.cshtml
@model SliderItem

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Category Creation Form</h4>
            <form class="forms-sample" method="post" asp-controller="Slider" asp-action="Update">
                <div class="form-group">
                    <label for="exampleInputUsername1" asp-for="Photo">Photo</label>
                    <input type="file" class="form-control" placeholder="Photo" asp-for="Photo">
                    <span class="text-danger" asp-validation-for="Photo"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
            </form>
        </div>
    </div>
</div>